**1. Arrays**

In [1]:
import numpy

def arrays(arr):
    return (numpy.array(arr[::-1],float))

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


**2. Shape and Reshape**

In [2]:
import numpy
print(numpy.reshape(numpy.array(input().split(),int),(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**3. Transpose and Flatten**

In [1]:
import numpy
N, M= map(int,input().split())
l=[]
for i in range(N):
    l.append(input().split())
arr = numpy.array(l,int)
print(numpy.transpose(arr))
print(arr.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [3]:
N, M=map(int, input().split())
arr=numpy.array([input().strip().split() for _ in range(N)], int)
print(numpy.transpose(arr))
print(arr.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


**4. Concatenate**

In [4]:
import numpy
n,m,p=map(int,input().split())
arr1=numpy.array([input().strip().split() for _ in range(n)], int)
arr2=numpy.array([input().strip().split() for _ in range(m)], int)
print(numpy.concatenate((arr1, arr2), axis=0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


**5. Zeros and Ones**

In [5]:
import numpy
tup=tuple(map(int, input().split()))
print (numpy.zeros(tup, int))
print (numpy.ones(tup, int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


**6. Eye and Identity**

In [6]:
import numpy
a,b=map(int,input().strip().split())
print (numpy.eye(a,b))

3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**7. Array Mathematics**

In [7]:
import numpy
N, M=map(int, input().strip().split())
A=numpy.array(input().strip().split(),int)
B=numpy.array(input().strip().split(),int)
print(A+B,A-B,A*B,A//B,A%B,A**B,sep="\n")

1 4
1 2 3 4
5 6 7 8
[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0 0 0 0]
[1 2 3 4]
[    1    64  2187 65536]


In [8]:
import numpy
N,M = map(int, input().split())
A,B= (numpy.array([input().split() for _ in range(N)], dtype=int) for _ in range(2))
print(A+B, A-B, A*B, A//B, A%B, A**B, sep='\n')

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


**8. Floor, Ceil and Rint**

In [9]:
import numpy
A=numpy.array(input().strip().split(), float)
print(numpy.floor(A),numpy.ceil(A),numpy.rint(A), sep="\n")

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


**9. Sum and Prod**

In [10]:
import numpy
N,M=map(int,input().strip().split())
l=[]
for _ in range(N):
    l.append(input().strip().split())
arr=numpy.array(l,int)
print(numpy.prod(numpy.sum(arr,axis=0),axis=0))

2 2
1 2
3 4
24


**10. Min and Max**

In [1]:
import numpy
N,M= map(int, input().strip().split())
arr=numpy.array([input().strip().split() for _ in range(N)],int)
print( numpy.max(numpy.min(arr, axis=1)))

4 2
2 5
3 7
1 3
4 0
3


**11. Mean, Var, and Std**

In [2]:
import numpy
N,M= map(int, input().strip().split())
arr=numpy.array([input().strip().split() for _ in range(N)],int)
print(numpy.mean(arr,axis=1), numpy.var(arr, axis=0), numpy.std(arr), sep="\n")

2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.118033988749895


**12. Dot and Cross**

In [3]:
import numpy
N=int(input().strip())
A=numpy.array([input().strip().split() for _ in range(N)],int)
B=numpy.array([input().strip().split() for _ in range(N)],int)
print(numpy.dot(A,B))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


**13. Inner and Outer**

In [4]:
import numpy
A=numpy.array(input().strip().split(),int)
B=numpy.array(input().strip().split(),int)
print(numpy.inner(A,B),numpy.outer(A,B), sep="\n")

0 1
2 3
3
[[0 0]
 [2 3]]


**14. Polynomials**

In [5]:
import numpy
P=numpy.array(input().strip().split(),float)
x=float(input())
print(numpy.polyval(P,x))

1.1 2 3
0
3.0


**15. Linear Algebra**

In [6]:
import numpy
N=int(input())
arr=numpy.array([input().strip().split() for _ in range(N)],float)
print(round(numpy.linalg.det(arr),2))

2
1.1 1.1
1.1 1.1
0.0
